/**
 * Generated by tsnapi — public API snapshot of `@devframes/self-inspect`
 */
// #region Interfaces
export interface ClientScriptInfo {
  dockId: string;
  dockTitle: string;
  dockType: string;
  script: ClientScriptEntry;
}
// #endregion

// #region Functions
export declare function selfInspect(): DevframeDefinition;
// #endregion

// #region Variables
export declare const rpcFunctions: readonly [{
  name: "self-inspect:get-docks";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<DevframeDockEntry[]>>>) | undefined;
  handler?: (() => Promise<DevframeDockEntry[]>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<DevframeDockEntry[]>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<DevframeDockEntry[]>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<DevframeDockEntry[]>>> | undefined;
}, {
  name: "self-inspect:get-rpc-functions";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<{
    name: string;
    type: any;
    cacheable: boolean;
    hasArgs: boolean;
    hasReturns: boolean;
    hasDump: boolean;
    hasSetup: boolean;
    hasHandler: boolean;
  }[]>>>) | undefined;
  handler?: (() => Promise<{
    name: string;
    type: any;
    cacheable: boolean;
    hasArgs: boolean;
    hasReturns: boolean;
    hasDump: boolean;
    hasSetup: boolean;
    hasHandler: boolean;
  }[]>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<{
    name: string;
    type: any;
    cacheable: boolean;
    hasArgs: boolean;
    hasReturns: boolean;
    hasDump: boolean;
    hasSetup: boolean;
    hasHandler: boolean;
  }[]>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<{
    name: string;
    type: any;
    cacheable: boolean;
    hasArgs: boolean;
    hasReturns: boolean;
    hasDump: boolean;
    hasSetup: boolean;
    hasHandler: boolean;
  }[]>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<{
    name: string;
    type: any;
    cacheable: boolean;
    hasArgs: boolean;
    hasReturns: boolean;
    hasDump: boolean;
    hasSetup: boolean;
    hasHandler: boolean;
  }[]>>> | undefined;
}, {
  name: "self-inspect:get-client-scripts";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<ClientScriptInfo[]>>>) | undefined;
  handler?: (() => Promise<ClientScriptInfo[]>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<ClientScriptInfo[]>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<ClientScriptInfo[]>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<ClientScriptInfo[]>>> | undefined;
}, {
  name: "self-inspect:get-auth-tokens";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<_$devframe_utils_shared_state0.ImmutableObject<{
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  }>[]>>>) | undefined;
  handler?: (() => Promise<_$devframe_utils_shared_state0.ImmutableObject<{
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  }>[]>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<_$devframe_utils_shared_state0.ImmutableObject<{
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  }>[]>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<_$devframe_utils_shared_state0.ImmutableObject<{
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  }>[]>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<_$devframe_utils_shared_state0.ImmutableObject<{
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  }>[]>>> | undefined;
}, {
  name: "self-inspect:get-shared-state-keys";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<string[]>>>) | undefined;
  handler?: (() => Promise<string[]>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<string[]>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<string[]>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<string[]>>> | undefined;
}, {
  name: "self-inspect:revoke-auth-token";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$_devframes_hub0.DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[authToken: string], Promise<void>>>) | undefined;
  handler?: ((authToken: string) => Promise<void>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[authToken: string], Promise<void>, _$_devframes_hub0.DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[authToken: string], Promise<void>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[authToken: string], Promise<void>>> | undefined;
}];
// #endregion